<div class="container">
    <div class="alert alert-danger">
        <p><strong>Erreur sur le site !</strong></p>
    </div>
    <p>Nous vous prions de nous excuser mais notre site a rencontré un problème.</p>
    <p>Merci de recharger la page ou de renouveller votre requête.</p>
    <p>Si le problème persiste, ne vous inquiétez pas nos développeur sont déjà au courant :)</p>
    <p>Vous pouvez nous laisser votre email et un petit message pour que nous vous informions quand le problème sera résolu !</p>

    <form name="sentMessage" id="contactForm" novalidate>
        <div class="control-group">
            <div class="form-group floating-label-form-group controls">
                <label>Votre nom</label>
                <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
                <p class="help-block text-danger"></p>
            </div>
        </div>
        <div class="control-group">
            <div class="form-group floating-label-form-group controls">
                <label>Votre email</label>
                <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
                <p class="help-block text-danger"></p>
            </div>
        </div>
        <div class="control-group">
            <div class="form-group floating-label-form-group controls">
                <label>Message</label>
                <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
                <p class="help-block text-danger"></p>
            </div>
        </div>
        <br>
        <div id="success"></div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary" id="sendMessageButton">Envoyer</button>
        </div>
    </form>
</div>