-- MySQL Script generated by MySQL Workbench
-- Thu Mar  5 13:54:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blogDigne
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema blogDigne
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blogDigne` DEFAULT CHARACTER SET utf8 ;
USE `blogDigne` ;

-- -----------------------------------------------------
-- Table `blogDigne`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogDigne`.`categorie` (
  `cat_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cat_title` VARCHAR(45) NOT NULL,
  `cat_description` VARCHAR(255) NULL,
  `cat_picture` VARCHAR(100) NULL,
  PRIMARY KEY (`cat_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogDigne`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogDigne`.`author` (
  `aut_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `aut_lastname` VARCHAR(45) NOT NULL,
  `aut_firstname` VARCHAR(45) NOT NULL,
  `aut_email` VARCHAR(100) NOT NULL,
  `aut_password` VARCHAR(255) NOT NULL,
  `aut_bio` VARCHAR(255) NULL,
  `aut_avatar` VARCHAR(255) NULL,
  `aut_valid` TINYINT NOT NULL DEFAULT 1,
  `aut_role` VARCHAR(45) NULL,
  PRIMARY KEY (`aut_id`),
  UNIQUE INDEX `aut_email_UNIQUE` (`aut_email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogDigne`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogDigne`.`article` (
  `art_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `art_title` VARCHAR(45) NOT NULL,
  `art_content` TEXT NULL,
  `art_created_date` DATETIME NOT NULL,
  `art_published_date` DATETIME NOT NULL,
  `art_picture` VARCHAR(100) NULL,
  `art_valid` TINYINT NOT NULL DEFAULT 1,
  `categorie_cat_id` INT UNSIGNED NOT NULL,
  `author_aut_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`art_id`),
  INDEX `fk_article_categorie_idx` (`categorie_cat_id` ASC),
  INDEX `fk_article_author1_idx` (`author_aut_id` ASC),
  CONSTRAINT `fk_article_categorie`
    FOREIGN KEY (`categorie_cat_id`)
    REFERENCES `blogDigne`.`categorie` (`cat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_article_author1`
    FOREIGN KEY (`author_aut_id`)
    REFERENCES `blogDigne`.`author` (`aut_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blogDigne`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `blogDigne`.`comment` (
  `com_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `com_pseudo` VARCHAR(45) NOT NULL,
  `com_email` VARCHAR(100) NOT NULL,
  `com_content` TEXT NOT NULL,
  `com_created_date` DATETIME NOT NULL DEFAULT NOW(),
  `com_valid` TINYINT NOT NULL DEFAULT 1,
  `article_art_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`com_id`),
  INDEX `fk_comment_article1_idx` (`article_art_id` ASC),
  CONSTRAINT `fk_comment_article1`
    FOREIGN KEY (`article_art_id`)
    REFERENCES `blogDigne`.`article` (`art_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
