<form action="addArticle.php" method="post" enctype="multipart/form-data">
    <?php if (isset($errors) && count($errors) > 0) : ?>
        <div class="alert alert-danger" role="alert">
            <ul>
                <?php foreach ($errors as $error) : ?>
                    <li class="erreur"><?= $error; ?></li>
                <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <fieldset>
        <div class="form-group">
            <label for="title">Titre</label>
            <input type="text" class="form-control" id="title" name="title" value="<?= $titleArticle ?>">
            <small id="titleHelp" class="form-text text-muted">Saisissez un titre pour votre article</small>
        </div>
        <div class="form-group">
            <label for="content">Contenu</label>
            <textarea class="form-control" id="content" name="content" rows="3"><?= $contentArticle ?></textarea>
            <small id="catHelp" class="form-text text-muted">Contenu de l'article</small>
        </div>
        <div class="form-group row">
            <label for="date" class="col-sm-4 col-form-label">Date et heure de publication</label>
            <div class="col-4">
                <input type="date" class="form-control" id="date" name="date" value="<?= $dateArticle ?>">
            </div>
            <div class="col-4">
                <input type="time" class="form-control" id="time" name="time" value="<?= $timeArticle ?>">
            </div>

        </div>
        <div class="form-group">
            <label for="category">Catégorie de l'article</label>
            <select class="form-control" id="category" name="category">
                <?php foreach ($categories as $category) : ?>
                    <option value="<?= $category['cat_id'] ?>" <?php if ($categoryArticle == $category['cat_id']) : ?>selected<?php endif; ?>>
                        <?= $category['cat_title'] ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <small id="catHelp" class="form-text text-muted">Sélectionnez une catégorie pour l'article</small>
        </div>
        <div class="form-group">
            <input type="hidden" name="MAX_FILE_SIZE" value="8388608‬">
            <label for="picture">Image de l'article</label>
            <input type="file" class="form-control-file" id="picture" name="picture" aria-describedby="fileHelp">
            <small id="fileHelp" class="form-text text-muted">Sélectionnez un fichier sur votre ordinateur</small>
        </div>
        <div class="form-group">
            <div class="custom-control custom-switch">
                <input type="checkbox" class="custom-control-input" name="valide" id="valide" <?php if ($valideArticle == true) : ?>checked="" <?php endif; ?>>
                <label class="custom-control-label" for="valide">Publier l'article</label>
                <small id="publieHelp" class="form-text text-muted">L'article sera mis en brouillon si vous décochez cette case !</small>
            </div>
        </div>
        <a href="listeArticle.php" class="btn btn-outline-primary">Annuler</a>
        <button type="submit" class="btn btn-primary">Créer l'article</button>

</form>