<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Admin blog - <?= $pageTitle ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="../css/picto.css">
    <link href="css/datatables.min.css" rel="stylesheet">
    <link href="css/styles.css" rel="stylesheet">
    <script src="../vendor/jquery/jquery.min.js"></script>
    <script src="../vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="js/dataTable/datatables.min.js"></script>
    <script src="js/tinyMCE/tinymce.min.js"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="index.php">Admin Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item <?php if ($view == 'index') : ?>active<?php endif; ?>">
                    <a class="nav-link" href="index.php">Accueil <?php if ($view == 'index') : ?><span class="sr-only">(current)</span><?php endif; ?></a>
                </li>
                <li class="nav-item dropdown <?php if ($view == 'addArticle' || $view == 'listeArticle' || $view == 'editArticle') : ?>active<?php endif; ?>">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarArticle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Articles
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarArticle">
                        <a class="dropdown-item <?php if ($view == 'listeArticle') : ?>active<?php endif; ?>" href="listeArticle.php">Liste</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item  <?php if ($view == 'addArticle') : ?>active<?php endif; ?>" href="addArticle.php">Ajouter</a>
                    </div>
                </li>
                <li class="nav-item dropdown <?php if ($view == 'addCategory' || $view == 'listeCategory' || $view == 'editCategory') : ?>active<?php endif; ?>">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarUser" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Catégories
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarUser">
                        <a class="dropdown-item <?php if ($view == 'listeCategory') : ?>active<?php endif; ?>" href="listeCategory.php">Liste</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item  <?php if ($view == 'addCategory') : ?>active<?php endif; ?>" href="addCategory.php">Ajouter</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="listeComment.php">Commentaires</a>
                </li>
                <li class="nav-item dropdown <?php if ($view == 'addUser' || $view == 'listeUser' || $view == 'editUser') : ?>active<?php endif; ?>">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarUser" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Utilisateurs
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarUser">
                        <a class="dropdown-item <?php if ($view == 'listeUser') : ?>active<?php endif; ?>" href="listeUser.php">Liste</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item  <?php if ($view == 'addUser') : ?>active<?php endif; ?>" href="addUser.php">Ajouter</a>
                    </div>
                </li>
            </ul>

            Bienvenue <?= $_SESSION['user']['name'] ?> - <a href="logout.php" class="btn btn-light">Logout</a>

        </div>
    </nav>
    <div class="container mb-4">
        <h1><?= $pageTitle ?></h1>
        <?php if (isset($flashbag) && $flashbag != false) : ?>

            <?php foreach ($flashbag as $message) : ?>
                <div class="alert alert-dismissible alert-<?= $message['level'] ?>" role="alert">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <p><?= $message['message'] ?></p>
                </div>
            <?php endforeach; ?>

        <?php endif; ?>

        <?php
        /** On inclu la vue */
        include('tpl/' . $view . '.phtml');
        ?>
    </div>

    <div class="modal fade" id="delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Suppression</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Êtes-vous sûr de vouloir supprimer cet element ?
                </div>
                <div class="modal-footer">
                    <form action="#" id="formdelete" method="POST">
                        <input type="hidden" value="" name="id" id="deleteId">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Supprimer</a>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <script>
        //DataTable
        $(document).ready(function() {
            $('#tableDonnee').DataTable({
                colReorder: true,
                stateSave: true,
                dom: 'Bfrtip',
                buttons: [
                    'pageLength',
                    'print',
                    'copyHtml5',
                    'csvHtml5',
                    'pdfHtml5',
                    'colvis'
                ],
                columnDefs: [{
                    "orderable": false,
                    "targets": -1
                }],
                language: {
                    url: 'js/dataTable/i18n/fr.json'
                }
            });
        });

        //TinyMCE
        tinymce.init({
            selector: 'textarea',
            height: 300,
            relative_urls: false,
            plugins: [
                "advlist autolink lists link image charmap print preview anchor",
                "searchreplace visualblocks code fullscreen",
                "insertdatetime media table paste imagetools wordcount"
            ],
            toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
            content_css: [
                'css/bootstrap.min.css',
                'css/editor.css'
            ],
            images_upload_url: '<?= URL ?>/lib/uploadTinyMce.php'
        });



        //Modal delete Bootstrap
        $('#delete').on('show.bs.modal', function(e) {
            $('#formdelete').attr("action", e.relatedTarget.href);
            $('#formdelete #deleteId').val(e.relatedTarget.dataset.id);
        });

        $('input:checkbox').change(function() {
            console.log($(this).prop('checked'));
        })
    </script>
</body>

</html>