<?php if (count($errors) > 0) :
    foreach ($errors as $error) : ?>

        <div class="alert alert-dismissible alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong><?= $error ?></strong>
        </div>

<?php
    endforeach;
endif ?>

<div class="container">
    <h1 class="text-primary">Ajouter Une Categorie</h1>
    <form action="addCat.php" method="POST" name="formfocus" enctype="multipart/form-data">
        <div class="form-group">
            <label for="cat_picture">image</label>
            <input type="file" name="cat_picture" id="cat_picture" class="form-control" value="<?= $pictureName ?>">

        </div>
        <div class="form-group">
            <label for="cat_title">Titre</label>
            <input type="text" name="cat_title" id="cat_title" class="form-control" value="<?= $title ?>" required>
        </div>
        <div class="form-group">
            <label for="cat_description">Description</label>
            <textarea name="cat_description" id="cat_description" required class="form-control"><?= $desc ?></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Ajouter</button>


    </form>
</div>