<main role="main" class="container">
    <h1 class="text-primary">Dashboard</h1>
    <div class="row">
        <div class="col-lg-4">
            <div class="card">
                <h5 class="card-header bg-info text-white">Visualisation rapide</h5>
                <div class="card-body">


                    <p class="card-text">pour voir tout de suite votre site</p>
                    <div class="r col-lg-12"><a href="#" class="btn btn-primary btn-lg btn-block">afficher votre site</a></div>
                </div>
            </div>
            <div class="card">
                <h5 class="card-header bg-info text-white">Actions rapide</h5>
                <div class="card-body">

                    <div class="col-lg-12">
                        <i class="icon-file-plus text-primary "></i>

                        <a href="addArticle.php">ajouter un article</a></div>
                    <div class="col-lg-11">
                        <i class="icon-plus-square  text-primary "></i>
                        <a href="addCat.php">ajouter une categorie</a></div>
                    <div class="col-lg-11">
                        <i class="icon-user-plus  text-primary "></i>
                        <a href="addUser.php">ajouter un utilisateur</a></div>



                </div>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="card">
                <h5 class="card-header bg-info text-white">Article rapide</h5>
                <div class="card-body">
                    <p>titre de l'article</p>
                    <input class="form-control" type="text" placeholder="Default input">
                    <p>categorie de l'article</p>
                    <select class="form-control">
                        <option>Jeux videos</option>
                        <option>The Legend of Zelda</option>
                        <option>Super Mario</option>
                        <option>Developpement Web</option>
                        <option>PHP</option>
                        <option>POO</option>
                        <option>JavaScript</option>
                    </select>
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1">Example textarea</label>
                        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                    </div>
                    <div class="custom-control custom-switch">
                        <input type="checkbox" class="custom-control-input" id="customSwitch1">
                        <label class="custom-control-label" for="customSwitch1">Publier l'article</label>
                        <small id="emailHelp" class="form-text text-muted">L'article sera mis en brouillon si vous decochez cette case !</small>
                        <div class="r col-lg-12"><a href="#" class="btn btn-primary  ">enregister</a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-7">
            <div class="card">
                <h5 class="card-header bg-info text-white">Liste des derniers articles</h5>
                <div class="card-body">
                    <ul class="list-group list-group-flush ">

                        <li class="list-group-item">

                            <i class=" big icon-toggle-right"></i>
                            <a href="#">Fred l'integrateur</a> <span class="badge badge-success">supermario</span>

                            <footer class="blockquote-footer text-align-right">De fabien selles</footer>
                        </li>


                        <li class="list-group-item">

                            <i class="  big icon-toggle-right "></i>
                            <a href="#">La POO en PHP en 16 minutes(ou moins)</a> <span class="badge badge-success">POO</span>
                            <footer class="blockquote-footer ">De fabien selles</footer>
                        </li>

                    </ul>


                </div>
            </div><a href="#" class="text-primary">voir tous les articles</a>
        </div>
        <div class="col-sm-5">
            <div class="card">
                <h5 class="card-header bg-info text-white">liste des derniers commentaires</h5>

                <ul class="list-group list-group-flush  ">
                    <li class="list-group-item">Cras justo odio Cras justo odio Cras justo odio Cras justo
                        <footer class="blockquote-footer text-right">De jean bob</footer>
                    </li>
                    <li class="list-group-item">Dapibus ac facilisis in Cras justo odio Cras justo odio
                        <footer class="blockquote-footer text-right">jean Karime</footer>
                    </li>
                    <li class="list-group-item">Vestibulum at eros Cras justo odio Cras justo odio
                        <footer class="blockquote-footer text-right">jean fred </footer>
                    </li>
                    <li class="list-group-item">Vestibulum at eros Cras justo odio Cras justo odio
                        <footer class="blockquote-footer text-right ">jeannine sabine </footer>
                    </li>
                </ul>




            </div>
            <a href="#" class="text-primary">voir tous les commentaires</a>
        </div>
    </div>
</main>