<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="../css/picto.css">
    <script src="../js/jquery-3.3.1.min.js"></script>
    <script src="../js/bootstrap.bundle.min.js"></script>

    <link rel="stylesheet" href="../css/style.css">
    <title>Document</title>

</head>

<body>


    <div class="quicontienttout">
        <form action="login.php" method="POST">
            <div class="fadeIn first  icone">
                <i class="icon-user "></i>
            </div>
            <?php if (count($errors) > 0) :
                foreach ($errors as $error) : ?>

                    <div class="alert alert-dismissible alert-danger">
                        <button type="button" class="close" data-dismiss="alert">&times;</button>
                        <strong><?= $error ?></strong>
                    </div>

            <?php
                endforeach;
            endif ?>

            <div class=" champ form-group ">

                <input type="email" class=" interieurchamp form-control" id="aut_email" name="aut_email" aria-describedby="emailHelp" placeholder="Enter email">
            </div>
            <div class=" champ form-group">
                <input type="password" class="interieurchamp form-control" id="aut_password" name="aut_password" placeholder="Password">
            </div>
            <button type="submit" class=" boutonlogin btn btn-primary">login</button>
            <div class="mdpoubli">
                <a href="#" target="_blank" rel="noopener noreferrer">mot de passe oublié?</a>
            </div>
        </form>
    </div>
</body>

</html>