<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Clean Blog - Start Bootstrap Theme</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="css/clean-blog.min.css" rel="stylesheet">

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="index.html">Start Bootstrap</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="post.php">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="admin/">admin</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="post.html">Sample Post</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="contact.html">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Header -->
    <header class="masthead" style="background-image: url('uploads/articles/<?= $donnees['art_picture'] ?>')">
        <div class=" overlay">
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="post-heading">
                        <h1><?= $donnees['art_title'] ?></h1>

                        <span class="meta">Posted by <?= $donnees['aut_name'] ?>

                            on <p><?= $donnees['art_published_date'] ?></p></span>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <p><?= $donnees['art_content'] ?>
    </div>
    <?php if (count($errors) > 0) :
        foreach ($errors as $error) : ?>

            <div class="alert alert-dismissible alert-danger">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong><?= $error ?></strong>
            </div>

    <?php
        endforeach;
    endif ?>
    <!-- Post Content -->

    <h1>Commentaires</h1>
    <table class="post-preview" style="display: flex">
        <th>pseudo</th>
        <th>commentaire</th>
        <th>email</th>
        <th>heure de publication</th>
        <?php
        foreach ($donnees2 as $donnee2) : ?>

            <tr>
                <td class=" post-subtitle">
                    <?= $donnee2['com_pseudo']; ?>
                </td>
                <td><?= $donnee2['com_description'] ?> </td>
                <td> <?= $donnee2['com_email']; ?></td>
                <td class="post-meta">
                    <?= $donnee2['com_time']; ?>

                </td>

            <?php
        endforeach;
            ?>
            </tr>
    </table>


    <hr>
    <form action="post.php" method="post">
        <label for="com_description">commentaire</label>
        <input type="text" name="com_description" id="com_description">
        <label for="com_pseudo"> pseudo</label>
        <input type="text" name="com_pseudo" id="com_pseudo">
        <label for="com_email">email</label>
        <input type="text" name="com_email" id="com_email">
        <input type="hidden" name="com_time" id="com_time" value="<?= date("Y-m-d H:i:s"); ?>">
        <input type="hidden" name="com_art_id" id="com_art_id" value="<?= $donnees['art_id'] ?>">
        <input type="submit" value="Envoyer">

    </form>
    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="js/clean-blog.min.js"></script>

</body>

</html>